// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ecommerce.Models
{
    public partial class paymentDetails
    {
        public int paymentDetailsId { get; set; }
        public bool? activeId { get; set; }
        public DateTime creationDate { get; set; }
        public int userId { get; set; }
        public string cardNumber { get; set; }

        public virtual users user { get; set; }
    }
}