// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ecommerce.Models
{
    public partial class productReview
    {
        public int productReviewId { get; set; }
        public bool? activeId { get; set; }
        public DateTime creationDate { get; set; }
        public int productId { get; set; }
        public int userId { get; set; }
        public int? price { get; set; }
        public string description { get; set; }

        public virtual products product { get; set; }
        public virtual users user { get; set; }
    }
}