// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ecommerce.Models
{
    public partial class stock
    {
        public int stockId { get; set; }
        public bool? activeId { get; set; }
        public DateTime creationDate { get; set; }
        public int productId { get; set; }
        public DateTime? restockDate { get; set; }
        public int? currentStock { get; set; }

        public virtual products product { get; set; }
    }
}