// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ecommerce.Models {
    public partial class users {
        public users() {
            paymentDetails = new HashSet<paymentDetails>();
            productReview = new HashSet<productReview>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int userId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public bool? activeId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime creationDate { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }

        public virtual ICollection<paymentDetails> paymentDetails { get; set; }
        public virtual ICollection<productReview> productReview { get; set; }
    }
}